### ISSUE TITLE
help

### ISSUE THREAD

**Issue by amiruldev20** [Nata4n/whatsapp-bot#4]
give me an example command
command title 
ex: song adfayta

**Comment by Nata4n** [comment]
Your command can have any name, here's an example: `sticker`. It is a command that converts media to sticker

**Comment by amiruldev20** [comment]
not that. I need an example command input
such as feature examples
play songs

**Comment by amiruldev20** [comment]
check https://github.com/Oreki-san/RIN
there is a command input feature like in the command/media folder. well i want it in your base

**Comment by Nata4n** [comment]
See how i used arguments in this [args-support](https://github.com/Nata4n/whatsapp-bot/tree/args-support/src) branch. The [`args`](https://github.com/Nata4n/whatsapp-bot/blob/args-support/src/commands/ping/ping.ts) parameter returns an array with the user's arguments. If you have any questions let me know
