### ISSUE TITLE
Scheduled messaging

### ISSUE THREAD

**Issue by am1ru1** [Nata4n/whatsapp-bot#8]
Clean and working framework.
Question: @Nata4n, do you have recommendation on how to implement scheduled messaging? I would like to received morning news through this framework. 
Shall this be implemented throughs Commands or Controller? how about the scheduling ?

**Comment by Nata4n** [comment]
Hey @am1ru1. Feel free to use any task schedule package. You can check [agenda](https://github.com/agenda/agenda) to create your tasks, also need a working [Mongo database.](https://mongodb.com)
